#!/usr/bin/env python3

import sys
from randomdef import randomDefinition


# Start by grabbing a word or phrase from the command line
inword = ' '.join(sys.argv[1:])

# Print the word or phrase, its definition, and attempt to print an example
print("\n")
exampleword = randomDefinition(inword, showexample=True)
exampleword.get_synset()
exampleword.print_output()
